export const LEGAL_SOURCE_TYPES = ['STATUTE', 'ORDINANCE', 'PRECEDENT', 'APPEAL_DECISION', 'BUDGET'];
export const DRAFT_DECISIONS = ['ACCEPT', 'PARTIAL', 'REJECT', 'TRANSFER', 'REQUEST_INFO'];
export const AUDIT_RISK_LEVELS = ['LOW', 'MODERATE', 'HIGH'];
